apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      containers:
      - name: kube-project-container
        image: techtanzila/kube-project:latest
        command: ["sleep", "3600"]   # <-- here under container spec, NOT metadata
        ports:
        - containerPort: 80
